FROM node:18

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Expose Vite port
EXPOSE 3000

# Start Vite dev server
CMD ["npm", "run", "dev"]
