# Use Node LTS
FROM node:18

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY src ./src
COPY .env .env

# Expose backend port
EXPOSE 5000

# Start backend
CMD ["npm", "run", "start"]
